// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_candy_shop.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ECandyShopRewardType int32

const (
	ECandyShopRewardType_k_eCandyShopRewardType_None        ECandyShopRewardType = 0
	ECandyShopRewardType_k_eCandyShopRewardType_Item        ECandyShopRewardType = 1
	ECandyShopRewardType_k_eCandyShopRewardType_EventAction ECandyShopRewardType = 2
)

var ECandyShopRewardType_name = map[int32]string{
	0: "k_eCandyShopRewardType_None",
	1: "k_eCandyShopRewardType_Item",
	2: "k_eCandyShopRewardType_EventAction",
}

var ECandyShopRewardType_value = map[string]int32{
	"k_eCandyShopRewardType_None":        0,
	"k_eCandyShopRewardType_Item":        1,
	"k_eCandyShopRewardType_EventAction": 2,
}

func (x ECandyShopRewardType) Enum() *ECandyShopRewardType {
	p := new(ECandyShopRewardType)
	*p = x
	return p
}

func (x ECandyShopRewardType) String() string {
	return proto.EnumName(ECandyShopRewardType_name, int32(x))
}

func (x *ECandyShopRewardType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECandyShopRewardType_value, data, "ECandyShopRewardType")
	if err != nil {
		return err
	}
	*x = ECandyShopRewardType(value)
	return nil
}

func (ECandyShopRewardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{0}
}

type CMsgClientToGCCandyShopGetUserDataResponse_EResponse int32

const (
	CMsgClientToGCCandyShopGetUserDataResponse_k_eInternalError CMsgClientToGCCandyShopGetUserDataResponse_EResponse = 0
	CMsgClientToGCCandyShopGetUserDataResponse_k_eSuccess       CMsgClientToGCCandyShopGetUserDataResponse_EResponse = 1
	CMsgClientToGCCandyShopGetUserDataResponse_k_eTooBusy       CMsgClientToGCCandyShopGetUserDataResponse_EResponse = 2
	CMsgClientToGCCandyShopGetUserDataResponse_k_eDisabled      CMsgClientToGCCandyShopGetUserDataResponse_EResponse = 3
	CMsgClientToGCCandyShopGetUserDataResponse_k_eTimeout       CMsgClientToGCCandyShopGetUserDataResponse_EResponse = 4
)

var CMsgClientToGCCandyShopGetUserDataResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCCandyShopGetUserDataResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCCandyShopGetUserDataResponse_EResponse) Enum() *CMsgClientToGCCandyShopGetUserDataResponse_EResponse {
	p := new(CMsgClientToGCCandyShopGetUserDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCCandyShopGetUserDataResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCCandyShopGetUserDataResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCCandyShopGetUserDataResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCCandyShopGetUserDataResponse_EResponse_value, data, "CMsgClientToGCCandyShopGetUserDataResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCCandyShopGetUserDataResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCCandyShopGetUserDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{9, 0}
}

type CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse int32

const (
	CMsgClientToGCCandyShopPurchaseRewardResponse_k_eInternalError CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = 0
	CMsgClientToGCCandyShopPurchaseRewardResponse_k_eSuccess       CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = 1
	CMsgClientToGCCandyShopPurchaseRewardResponse_k_eTooBusy       CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = 2
	CMsgClientToGCCandyShopPurchaseRewardResponse_k_eDisabled      CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = 3
	CMsgClientToGCCandyShopPurchaseRewardResponse_k_eTimeout       CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = 4
)

var CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse) Enum() *CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse {
	p := new(CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_value, data, "CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{12, 0}
}

type CMsgClientToGCCandyShopDoExchangeResponse_EResponse int32

const (
	CMsgClientToGCCandyShopDoExchangeResponse_k_eInternalError CMsgClientToGCCandyShopDoExchangeResponse_EResponse = 0
	CMsgClientToGCCandyShopDoExchangeResponse_k_eSuccess       CMsgClientToGCCandyShopDoExchangeResponse_EResponse = 1
	CMsgClientToGCCandyShopDoExchangeResponse_k_eTooBusy       CMsgClientToGCCandyShopDoExchangeResponse_EResponse = 2
	CMsgClientToGCCandyShopDoExchangeResponse_k_eDisabled      CMsgClientToGCCandyShopDoExchangeResponse_EResponse = 3
	CMsgClientToGCCandyShopDoExchangeResponse_k_eTimeout       CMsgClientToGCCandyShopDoExchangeResponse_EResponse = 4
)

var CMsgClientToGCCandyShopDoExchangeResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCCandyShopDoExchangeResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCCandyShopDoExchangeResponse_EResponse) Enum() *CMsgClientToGCCandyShopDoExchangeResponse_EResponse {
	p := new(CMsgClientToGCCandyShopDoExchangeResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCCandyShopDoExchangeResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCCandyShopDoExchangeResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCCandyShopDoExchangeResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCCandyShopDoExchangeResponse_EResponse_value, data, "CMsgClientToGCCandyShopDoExchangeResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCCandyShopDoExchangeResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCCandyShopDoExchangeResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{14, 0}
}

type CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse int32

const (
	CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eInternalError CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = 0
	CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eSuccess       CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = 1
	CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eTooBusy       CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = 2
	CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eDisabled      CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = 3
	CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eTimeout       CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = 4
)

var CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse) Enum() *CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse {
	p := new(CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_value, data, "CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{16, 0}
}

type CMsgClientToGCCandyShopRerollRewardResponse_EResponse int32

const (
	CMsgClientToGCCandyShopRerollRewardResponse_k_eInternalError CMsgClientToGCCandyShopRerollRewardResponse_EResponse = 0
	CMsgClientToGCCandyShopRerollRewardResponse_k_eSuccess       CMsgClientToGCCandyShopRerollRewardResponse_EResponse = 1
	CMsgClientToGCCandyShopRerollRewardResponse_k_eTooBusy       CMsgClientToGCCandyShopRerollRewardResponse_EResponse = 2
	CMsgClientToGCCandyShopRerollRewardResponse_k_eDisabled      CMsgClientToGCCandyShopRerollRewardResponse_EResponse = 3
	CMsgClientToGCCandyShopRerollRewardResponse_k_eTimeout       CMsgClientToGCCandyShopRerollRewardResponse_EResponse = 4
)

var CMsgClientToGCCandyShopRerollRewardResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
}

var CMsgClientToGCCandyShopRerollRewardResponse_EResponse_value = map[string]int32{
	"k_eInternalError": 0,
	"k_eSuccess":       1,
	"k_eTooBusy":       2,
	"k_eDisabled":      3,
	"k_eTimeout":       4,
}

func (x CMsgClientToGCCandyShopRerollRewardResponse_EResponse) Enum() *CMsgClientToGCCandyShopRerollRewardResponse_EResponse {
	p := new(CMsgClientToGCCandyShopRerollRewardResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCCandyShopRerollRewardResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCCandyShopRerollRewardResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCCandyShopRerollRewardResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCCandyShopRerollRewardResponse_EResponse_value, data, "CMsgClientToGCCandyShopRerollRewardResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCCandyShopRerollRewardResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCCandyShopRerollRewardResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{18, 0}
}

type CMsgCandyShopCandyCount struct {
	CandyType            *uint32  `protobuf:"varint,1,opt,name=candy_type,json=candyType" json:"candy_type,omitempty"`
	CandyCount           *uint32  `protobuf:"varint,2,opt,name=candy_count,json=candyCount" json:"candy_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgCandyShopCandyCount) Reset()         { *m = CMsgCandyShopCandyCount{} }
func (m *CMsgCandyShopCandyCount) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopCandyCount) ProtoMessage()    {}
func (*CMsgCandyShopCandyCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{0}
}

func (m *CMsgCandyShopCandyCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopCandyCount.Unmarshal(m, b)
}
func (m *CMsgCandyShopCandyCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopCandyCount.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopCandyCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopCandyCount.Merge(m, src)
}
func (m *CMsgCandyShopCandyCount) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopCandyCount.Size(m)
}
func (m *CMsgCandyShopCandyCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopCandyCount.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopCandyCount proto.InternalMessageInfo

func (m *CMsgCandyShopCandyCount) GetCandyType() uint32 {
	if m != nil && m.CandyType != nil {
		return *m.CandyType
	}
	return 0
}

func (m *CMsgCandyShopCandyCount) GetCandyCount() uint32 {
	if m != nil && m.CandyCount != nil {
		return *m.CandyCount
	}
	return 0
}

type CMsgCandyShopCandyQuantity struct {
	CandyCounts          []*CMsgCandyShopCandyCount `protobuf:"bytes,1,rep,name=candy_counts,json=candyCounts" json:"candy_counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CMsgCandyShopCandyQuantity) Reset()         { *m = CMsgCandyShopCandyQuantity{} }
func (m *CMsgCandyShopCandyQuantity) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopCandyQuantity) ProtoMessage()    {}
func (*CMsgCandyShopCandyQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{1}
}

func (m *CMsgCandyShopCandyQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopCandyQuantity.Unmarshal(m, b)
}
func (m *CMsgCandyShopCandyQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopCandyQuantity.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopCandyQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopCandyQuantity.Merge(m, src)
}
func (m *CMsgCandyShopCandyQuantity) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopCandyQuantity.Size(m)
}
func (m *CMsgCandyShopCandyQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopCandyQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopCandyQuantity proto.InternalMessageInfo

func (m *CMsgCandyShopCandyQuantity) GetCandyCounts() []*CMsgCandyShopCandyCount {
	if m != nil {
		return m.CandyCounts
	}
	return nil
}

type CMsgCandyShopExchangeRecipe struct {
	RecipeId             *uint64                     `protobuf:"varint,1,opt,name=recipe_id,json=recipeId" json:"recipe_id,omitempty"`
	Input                *CMsgCandyShopCandyQuantity `protobuf:"bytes,2,opt,name=input" json:"input,omitempty"`
	Output               *CMsgCandyShopCandyQuantity `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgCandyShopExchangeRecipe) Reset()         { *m = CMsgCandyShopExchangeRecipe{} }
func (m *CMsgCandyShopExchangeRecipe) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopExchangeRecipe) ProtoMessage()    {}
func (*CMsgCandyShopExchangeRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{2}
}

func (m *CMsgCandyShopExchangeRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopExchangeRecipe.Unmarshal(m, b)
}
func (m *CMsgCandyShopExchangeRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopExchangeRecipe.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopExchangeRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopExchangeRecipe.Merge(m, src)
}
func (m *CMsgCandyShopExchangeRecipe) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopExchangeRecipe.Size(m)
}
func (m *CMsgCandyShopExchangeRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopExchangeRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopExchangeRecipe proto.InternalMessageInfo

func (m *CMsgCandyShopExchangeRecipe) GetRecipeId() uint64 {
	if m != nil && m.RecipeId != nil {
		return *m.RecipeId
	}
	return 0
}

func (m *CMsgCandyShopExchangeRecipe) GetInput() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *CMsgCandyShopExchangeRecipe) GetOutput() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Output
	}
	return nil
}

type CMsgCandyShopRewardData_Item struct {
	ItemDef              *uint32  `protobuf:"varint,1,opt,name=item_def,json=itemDef" json:"item_def,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgCandyShopRewardData_Item) Reset()         { *m = CMsgCandyShopRewardData_Item{} }
func (m *CMsgCandyShopRewardData_Item) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopRewardData_Item) ProtoMessage()    {}
func (*CMsgCandyShopRewardData_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{3}
}

func (m *CMsgCandyShopRewardData_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopRewardData_Item.Unmarshal(m, b)
}
func (m *CMsgCandyShopRewardData_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopRewardData_Item.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopRewardData_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopRewardData_Item.Merge(m, src)
}
func (m *CMsgCandyShopRewardData_Item) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopRewardData_Item.Size(m)
}
func (m *CMsgCandyShopRewardData_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopRewardData_Item.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopRewardData_Item proto.InternalMessageInfo

func (m *CMsgCandyShopRewardData_Item) GetItemDef() uint32 {
	if m != nil && m.ItemDef != nil {
		return *m.ItemDef
	}
	return 0
}

type CMsgCandyShopRewardData_EventAction struct {
	EventId              *EEvent  `protobuf:"varint,1,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	ActionId             *uint32  `protobuf:"varint,2,opt,name=action_id,json=actionId" json:"action_id,omitempty"`
	Quantity             *uint32  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgCandyShopRewardData_EventAction) Reset()         { *m = CMsgCandyShopRewardData_EventAction{} }
func (m *CMsgCandyShopRewardData_EventAction) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopRewardData_EventAction) ProtoMessage()    {}
func (*CMsgCandyShopRewardData_EventAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{4}
}

func (m *CMsgCandyShopRewardData_EventAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopRewardData_EventAction.Unmarshal(m, b)
}
func (m *CMsgCandyShopRewardData_EventAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopRewardData_EventAction.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopRewardData_EventAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopRewardData_EventAction.Merge(m, src)
}
func (m *CMsgCandyShopRewardData_EventAction) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopRewardData_EventAction.Size(m)
}
func (m *CMsgCandyShopRewardData_EventAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopRewardData_EventAction.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopRewardData_EventAction proto.InternalMessageInfo

const Default_CMsgCandyShopRewardData_EventAction_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgCandyShopRewardData_EventAction) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgCandyShopRewardData_EventAction_EventId
}

func (m *CMsgCandyShopRewardData_EventAction) GetActionId() uint32 {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return 0
}

func (m *CMsgCandyShopRewardData_EventAction) GetQuantity() uint32 {
	if m != nil && m.Quantity != nil {
		return *m.Quantity
	}
	return 0
}

type CMsgCandyShopRewardItem struct {
	RewardType           *ECandyShopRewardType                `protobuf:"varint,1,opt,name=reward_type,json=rewardType,enum=protocol.ECandyShopRewardType,def=0" json:"reward_type,omitempty"`
	ItemData             *CMsgCandyShopRewardData_Item        `protobuf:"bytes,2,opt,name=item_data,json=itemData" json:"item_data,omitempty"`
	EventActionData      *CMsgCandyShopRewardData_EventAction `protobuf:"bytes,3,opt,name=event_action_data,json=eventActionData" json:"event_action_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *CMsgCandyShopRewardItem) Reset()         { *m = CMsgCandyShopRewardItem{} }
func (m *CMsgCandyShopRewardItem) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopRewardItem) ProtoMessage()    {}
func (*CMsgCandyShopRewardItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{5}
}

func (m *CMsgCandyShopRewardItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopRewardItem.Unmarshal(m, b)
}
func (m *CMsgCandyShopRewardItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopRewardItem.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopRewardItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopRewardItem.Merge(m, src)
}
func (m *CMsgCandyShopRewardItem) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopRewardItem.Size(m)
}
func (m *CMsgCandyShopRewardItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopRewardItem.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopRewardItem proto.InternalMessageInfo

const Default_CMsgCandyShopRewardItem_RewardType ECandyShopRewardType = ECandyShopRewardType_k_eCandyShopRewardType_None

func (m *CMsgCandyShopRewardItem) GetRewardType() ECandyShopRewardType {
	if m != nil && m.RewardType != nil {
		return *m.RewardType
	}
	return Default_CMsgCandyShopRewardItem_RewardType
}

func (m *CMsgCandyShopRewardItem) GetItemData() *CMsgCandyShopRewardData_Item {
	if m != nil {
		return m.ItemData
	}
	return nil
}

func (m *CMsgCandyShopRewardItem) GetEventActionData() *CMsgCandyShopRewardData_EventAction {
	if m != nil {
		return m.EventActionData
	}
	return nil
}

type CMsgCandyShopReward struct {
	RewardId             *uint64                     `protobuf:"varint,1,opt,name=reward_id,json=rewardId" json:"reward_id,omitempty"`
	Price                *CMsgCandyShopCandyQuantity `protobuf:"bytes,2,opt,name=price" json:"price,omitempty"`
	Reward               *CMsgCandyShopRewardItem    `protobuf:"bytes,3,opt,name=reward" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgCandyShopReward) Reset()         { *m = CMsgCandyShopReward{} }
func (m *CMsgCandyShopReward) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopReward) ProtoMessage()    {}
func (*CMsgCandyShopReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{6}
}

func (m *CMsgCandyShopReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopReward.Unmarshal(m, b)
}
func (m *CMsgCandyShopReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopReward.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopReward.Merge(m, src)
}
func (m *CMsgCandyShopReward) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopReward.Size(m)
}
func (m *CMsgCandyShopReward) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopReward.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopReward proto.InternalMessageInfo

func (m *CMsgCandyShopReward) GetRewardId() uint64 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

func (m *CMsgCandyShopReward) GetPrice() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *CMsgCandyShopReward) GetReward() *CMsgCandyShopRewardItem {
	if m != nil {
		return m.Reward
	}
	return nil
}

type CMsgCandyShopUserData struct {
	InventorySize          *uint32                        `protobuf:"varint,1,opt,name=inventory_size,json=inventorySize" json:"inventory_size,omitempty"`
	Inventory              *CMsgCandyShopCandyQuantity    `protobuf:"bytes,2,opt,name=inventory" json:"inventory,omitempty"`
	ExchangeResetTimestamp *uint32                        `protobuf:"fixed32,3,opt,name=exchange_reset_timestamp,json=exchangeResetTimestamp" json:"exchange_reset_timestamp,omitempty"`
	ExchangeRecipes        []*CMsgCandyShopExchangeRecipe `protobuf:"bytes,4,rep,name=exchange_recipes,json=exchangeRecipes" json:"exchange_recipes,omitempty"`
	ActiveRewards          []*CMsgCandyShopReward         `protobuf:"bytes,5,rep,name=active_rewards,json=activeRewards" json:"active_rewards,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *CMsgCandyShopUserData) Reset()         { *m = CMsgCandyShopUserData{} }
func (m *CMsgCandyShopUserData) String() string { return proto.CompactTextString(m) }
func (*CMsgCandyShopUserData) ProtoMessage()    {}
func (*CMsgCandyShopUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{7}
}

func (m *CMsgCandyShopUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCandyShopUserData.Unmarshal(m, b)
}
func (m *CMsgCandyShopUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCandyShopUserData.Marshal(b, m, deterministic)
}
func (m *CMsgCandyShopUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCandyShopUserData.Merge(m, src)
}
func (m *CMsgCandyShopUserData) XXX_Size() int {
	return xxx_messageInfo_CMsgCandyShopUserData.Size(m)
}
func (m *CMsgCandyShopUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCandyShopUserData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCandyShopUserData proto.InternalMessageInfo

func (m *CMsgCandyShopUserData) GetInventorySize() uint32 {
	if m != nil && m.InventorySize != nil {
		return *m.InventorySize
	}
	return 0
}

func (m *CMsgCandyShopUserData) GetInventory() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *CMsgCandyShopUserData) GetExchangeResetTimestamp() uint32 {
	if m != nil && m.ExchangeResetTimestamp != nil {
		return *m.ExchangeResetTimestamp
	}
	return 0
}

func (m *CMsgCandyShopUserData) GetExchangeRecipes() []*CMsgCandyShopExchangeRecipe {
	if m != nil {
		return m.ExchangeRecipes
	}
	return nil
}

func (m *CMsgCandyShopUserData) GetActiveRewards() []*CMsgCandyShopReward {
	if m != nil {
		return m.ActiveRewards
	}
	return nil
}

type CMsgClientToGCCandyShopGetUserData struct {
	CandyShopId          *uint32  `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCCandyShopGetUserData) Reset()         { *m = CMsgClientToGCCandyShopGetUserData{} }
func (m *CMsgClientToGCCandyShopGetUserData) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopGetUserData) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopGetUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{8}
}

func (m *CMsgClientToGCCandyShopGetUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserData.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopGetUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserData.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopGetUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopGetUserData.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopGetUserData) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserData.Size(m)
}
func (m *CMsgClientToGCCandyShopGetUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopGetUserData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopGetUserData proto.InternalMessageInfo

func (m *CMsgClientToGCCandyShopGetUserData) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

type CMsgClientToGCCandyShopGetUserDataResponse struct {
	Response             *CMsgClientToGCCandyShopGetUserDataResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCCandyShopGetUserDataResponse_EResponse,def=0" json:"response,omitempty"`
	UserData             *CMsgCandyShopUserData                                `protobuf:"bytes,2,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *CMsgClientToGCCandyShopGetUserDataResponse) Reset() {
	*m = CMsgClientToGCCandyShopGetUserDataResponse{}
}
func (m *CMsgClientToGCCandyShopGetUserDataResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCCandyShopGetUserDataResponse) ProtoMessage() {}
func (*CMsgClientToGCCandyShopGetUserDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{9}
}

func (m *CMsgClientToGCCandyShopGetUserDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopGetUserDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopGetUserDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopGetUserDataResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse.Size(m)
}
func (m *CMsgClientToGCCandyShopGetUserDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopGetUserDataResponse proto.InternalMessageInfo

const Default_CMsgClientToGCCandyShopGetUserDataResponse_Response CMsgClientToGCCandyShopGetUserDataResponse_EResponse = CMsgClientToGCCandyShopGetUserDataResponse_k_eInternalError

func (m *CMsgClientToGCCandyShopGetUserDataResponse) GetResponse() CMsgClientToGCCandyShopGetUserDataResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCCandyShopGetUserDataResponse_Response
}

func (m *CMsgClientToGCCandyShopGetUserDataResponse) GetUserData() *CMsgCandyShopUserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type CMsgGCToClientCandyShopUserDataUpdated struct {
	CandyShopId          *uint32                `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	UserData             *CMsgCandyShopUserData `protobuf:"bytes,2,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CMsgGCToClientCandyShopUserDataUpdated) Reset() {
	*m = CMsgGCToClientCandyShopUserDataUpdated{}
}
func (m *CMsgGCToClientCandyShopUserDataUpdated) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientCandyShopUserDataUpdated) ProtoMessage()    {}
func (*CMsgGCToClientCandyShopUserDataUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{10}
}

func (m *CMsgGCToClientCandyShopUserDataUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated.Unmarshal(m, b)
}
func (m *CMsgGCToClientCandyShopUserDataUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientCandyShopUserDataUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated.Merge(m, src)
}
func (m *CMsgGCToClientCandyShopUserDataUpdated) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated.Size(m)
}
func (m *CMsgGCToClientCandyShopUserDataUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientCandyShopUserDataUpdated proto.InternalMessageInfo

func (m *CMsgGCToClientCandyShopUserDataUpdated) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

func (m *CMsgGCToClientCandyShopUserDataUpdated) GetUserData() *CMsgCandyShopUserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type CMsgClientToGCCandyShopPurchaseReward struct {
	CandyShopId          *uint32  `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	RewardId             *uint64  `protobuf:"varint,2,opt,name=reward_id,json=rewardId" json:"reward_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCCandyShopPurchaseReward) Reset()         { *m = CMsgClientToGCCandyShopPurchaseReward{} }
func (m *CMsgClientToGCCandyShopPurchaseReward) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopPurchaseReward) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopPurchaseReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{11}
}

func (m *CMsgClientToGCCandyShopPurchaseReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopPurchaseReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopPurchaseReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopPurchaseReward) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward.Size(m)
}
func (m *CMsgClientToGCCandyShopPurchaseReward) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopPurchaseReward proto.InternalMessageInfo

func (m *CMsgClientToGCCandyShopPurchaseReward) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

func (m *CMsgClientToGCCandyShopPurchaseReward) GetRewardId() uint64 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

type CMsgClientToGCCandyShopPurchaseRewardResponse struct {
	Response             *CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) Reset() {
	*m = CMsgClientToGCCandyShopPurchaseRewardResponse{}
}
func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCCandyShopPurchaseRewardResponse) ProtoMessage() {}
func (*CMsgClientToGCCandyShopPurchaseRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{12}
}

func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse.Size(m)
}
func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopPurchaseRewardResponse proto.InternalMessageInfo

const Default_CMsgClientToGCCandyShopPurchaseRewardResponse_Response CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse = CMsgClientToGCCandyShopPurchaseRewardResponse_k_eInternalError

func (m *CMsgClientToGCCandyShopPurchaseRewardResponse) GetResponse() CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCCandyShopPurchaseRewardResponse_Response
}

type CMsgClientToGCCandyShopDoExchange struct {
	CandyShopId          *uint32  `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	RecipeId             *uint64  `protobuf:"varint,2,opt,name=recipe_id,json=recipeId" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCCandyShopDoExchange) Reset()         { *m = CMsgClientToGCCandyShopDoExchange{} }
func (m *CMsgClientToGCCandyShopDoExchange) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopDoExchange) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopDoExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{13}
}

func (m *CMsgClientToGCCandyShopDoExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchange.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopDoExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchange.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopDoExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopDoExchange.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopDoExchange) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchange.Size(m)
}
func (m *CMsgClientToGCCandyShopDoExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopDoExchange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopDoExchange proto.InternalMessageInfo

func (m *CMsgClientToGCCandyShopDoExchange) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

func (m *CMsgClientToGCCandyShopDoExchange) GetRecipeId() uint64 {
	if m != nil && m.RecipeId != nil {
		return *m.RecipeId
	}
	return 0
}

type CMsgClientToGCCandyShopDoExchangeResponse struct {
	Response             *CMsgClientToGCCandyShopDoExchangeResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCCandyShopDoExchangeResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *CMsgClientToGCCandyShopDoExchangeResponse) Reset() {
	*m = CMsgClientToGCCandyShopDoExchangeResponse{}
}
func (m *CMsgClientToGCCandyShopDoExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopDoExchangeResponse) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopDoExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{14}
}

func (m *CMsgClientToGCCandyShopDoExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopDoExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopDoExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopDoExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse.Size(m)
}
func (m *CMsgClientToGCCandyShopDoExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopDoExchangeResponse proto.InternalMessageInfo

const Default_CMsgClientToGCCandyShopDoExchangeResponse_Response CMsgClientToGCCandyShopDoExchangeResponse_EResponse = CMsgClientToGCCandyShopDoExchangeResponse_k_eInternalError

func (m *CMsgClientToGCCandyShopDoExchangeResponse) GetResponse() CMsgClientToGCCandyShopDoExchangeResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCCandyShopDoExchangeResponse_Response
}

type CMsgClientToGCCandyShopDoVariableExchange struct {
	CandyShopId          *uint32                     `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	Input                *CMsgCandyShopCandyQuantity `protobuf:"bytes,2,opt,name=input" json:"input,omitempty"`
	Output               *CMsgCandyShopCandyQuantity `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgClientToGCCandyShopDoVariableExchange) Reset() {
	*m = CMsgClientToGCCandyShopDoVariableExchange{}
}
func (m *CMsgClientToGCCandyShopDoVariableExchange) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopDoVariableExchange) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopDoVariableExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{15}
}

func (m *CMsgClientToGCCandyShopDoVariableExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopDoVariableExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopDoVariableExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopDoVariableExchange) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange.Size(m)
}
func (m *CMsgClientToGCCandyShopDoVariableExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchange proto.InternalMessageInfo

func (m *CMsgClientToGCCandyShopDoVariableExchange) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

func (m *CMsgClientToGCCandyShopDoVariableExchange) GetInput() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *CMsgClientToGCCandyShopDoVariableExchange) GetOutput() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Output
	}
	return nil
}

type CMsgClientToGCCandyShopDoVariableExchangeResponse struct {
	Response             *CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) Reset() {
	*m = CMsgClientToGCCandyShopDoVariableExchangeResponse{}
}
func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCCandyShopDoVariableExchangeResponse) ProtoMessage() {}
func (*CMsgClientToGCCandyShopDoVariableExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{16}
}

func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse.Size(m)
}
func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopDoVariableExchangeResponse proto.InternalMessageInfo

const Default_CMsgClientToGCCandyShopDoVariableExchangeResponse_Response CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse = CMsgClientToGCCandyShopDoVariableExchangeResponse_k_eInternalError

func (m *CMsgClientToGCCandyShopDoVariableExchangeResponse) GetResponse() CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCCandyShopDoVariableExchangeResponse_Response
}

type CMsgClientToGCCandyShopRerollReward struct {
	CandyShopId          *uint32                     `protobuf:"varint,1,opt,name=candy_shop_id,json=candyShopId" json:"candy_shop_id,omitempty"`
	RewardId             *uint64                     `protobuf:"varint,2,opt,name=reward_id,json=rewardId" json:"reward_id,omitempty"`
	Price                *CMsgCandyShopCandyQuantity `protobuf:"bytes,3,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgClientToGCCandyShopRerollReward) Reset()         { *m = CMsgClientToGCCandyShopRerollReward{} }
func (m *CMsgClientToGCCandyShopRerollReward) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCCandyShopRerollReward) ProtoMessage()    {}
func (*CMsgClientToGCCandyShopRerollReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{17}
}

func (m *CMsgClientToGCCandyShopRerollReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollReward.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopRerollReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollReward.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopRerollReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopRerollReward.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopRerollReward) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollReward.Size(m)
}
func (m *CMsgClientToGCCandyShopRerollReward) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopRerollReward.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopRerollReward proto.InternalMessageInfo

func (m *CMsgClientToGCCandyShopRerollReward) GetCandyShopId() uint32 {
	if m != nil && m.CandyShopId != nil {
		return *m.CandyShopId
	}
	return 0
}

func (m *CMsgClientToGCCandyShopRerollReward) GetRewardId() uint64 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

func (m *CMsgClientToGCCandyShopRerollReward) GetPrice() *CMsgCandyShopCandyQuantity {
	if m != nil {
		return m.Price
	}
	return nil
}

type CMsgClientToGCCandyShopRerollRewardResponse struct {
	Response             *CMsgClientToGCCandyShopRerollRewardResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCCandyShopRerollRewardResponse_EResponse,def=0" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *CMsgClientToGCCandyShopRerollRewardResponse) Reset() {
	*m = CMsgClientToGCCandyShopRerollRewardResponse{}
}
func (m *CMsgClientToGCCandyShopRerollRewardResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCCandyShopRerollRewardResponse) ProtoMessage() {}
func (*CMsgClientToGCCandyShopRerollRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_132364ac0874755d, []int{18}
}

func (m *CMsgClientToGCCandyShopRerollRewardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCCandyShopRerollRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCCandyShopRerollRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse.Merge(m, src)
}
func (m *CMsgClientToGCCandyShopRerollRewardResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse.Size(m)
}
func (m *CMsgClientToGCCandyShopRerollRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCCandyShopRerollRewardResponse proto.InternalMessageInfo

const Default_CMsgClientToGCCandyShopRerollRewardResponse_Response CMsgClientToGCCandyShopRerollRewardResponse_EResponse = CMsgClientToGCCandyShopRerollRewardResponse_k_eInternalError

func (m *CMsgClientToGCCandyShopRerollRewardResponse) GetResponse() CMsgClientToGCCandyShopRerollRewardResponse_EResponse {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_CMsgClientToGCCandyShopRerollRewardResponse_Response
}

func init() {
	proto.RegisterEnum("protocol.ECandyShopRewardType", ECandyShopRewardType_name, ECandyShopRewardType_value)
	proto.RegisterEnum("protocol.CMsgClientToGCCandyShopGetUserDataResponse_EResponse", CMsgClientToGCCandyShopGetUserDataResponse_EResponse_name, CMsgClientToGCCandyShopGetUserDataResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse", CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_name, CMsgClientToGCCandyShopPurchaseRewardResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCCandyShopDoExchangeResponse_EResponse", CMsgClientToGCCandyShopDoExchangeResponse_EResponse_name, CMsgClientToGCCandyShopDoExchangeResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse", CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_name, CMsgClientToGCCandyShopDoVariableExchangeResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCCandyShopRerollRewardResponse_EResponse", CMsgClientToGCCandyShopRerollRewardResponse_EResponse_name, CMsgClientToGCCandyShopRerollRewardResponse_EResponse_value)
	proto.RegisterType((*CMsgCandyShopCandyCount)(nil), "protocol.CMsgCandyShopCandyCount")
	proto.RegisterType((*CMsgCandyShopCandyQuantity)(nil), "protocol.CMsgCandyShopCandyQuantity")
	proto.RegisterType((*CMsgCandyShopExchangeRecipe)(nil), "protocol.CMsgCandyShopExchangeRecipe")
	proto.RegisterType((*CMsgCandyShopRewardData_Item)(nil), "protocol.CMsgCandyShopRewardData_Item")
	proto.RegisterType((*CMsgCandyShopRewardData_EventAction)(nil), "protocol.CMsgCandyShopRewardData_EventAction")
	proto.RegisterType((*CMsgCandyShopRewardItem)(nil), "protocol.CMsgCandyShopRewardItem")
	proto.RegisterType((*CMsgCandyShopReward)(nil), "protocol.CMsgCandyShopReward")
	proto.RegisterType((*CMsgCandyShopUserData)(nil), "protocol.CMsgCandyShopUserData")
	proto.RegisterType((*CMsgClientToGCCandyShopGetUserData)(nil), "protocol.CMsgClientToGCCandyShopGetUserData")
	proto.RegisterType((*CMsgClientToGCCandyShopGetUserDataResponse)(nil), "protocol.CMsgClientToGCCandyShopGetUserDataResponse")
	proto.RegisterType((*CMsgGCToClientCandyShopUserDataUpdated)(nil), "protocol.CMsgGCToClientCandyShopUserDataUpdated")
	proto.RegisterType((*CMsgClientToGCCandyShopPurchaseReward)(nil), "protocol.CMsgClientToGCCandyShopPurchaseReward")
	proto.RegisterType((*CMsgClientToGCCandyShopPurchaseRewardResponse)(nil), "protocol.CMsgClientToGCCandyShopPurchaseRewardResponse")
	proto.RegisterType((*CMsgClientToGCCandyShopDoExchange)(nil), "protocol.CMsgClientToGCCandyShopDoExchange")
	proto.RegisterType((*CMsgClientToGCCandyShopDoExchangeResponse)(nil), "protocol.CMsgClientToGCCandyShopDoExchangeResponse")
	proto.RegisterType((*CMsgClientToGCCandyShopDoVariableExchange)(nil), "protocol.CMsgClientToGCCandyShopDoVariableExchange")
	proto.RegisterType((*CMsgClientToGCCandyShopDoVariableExchangeResponse)(nil), "protocol.CMsgClientToGCCandyShopDoVariableExchangeResponse")
	proto.RegisterType((*CMsgClientToGCCandyShopRerollReward)(nil), "protocol.CMsgClientToGCCandyShopRerollReward")
	proto.RegisterType((*CMsgClientToGCCandyShopRerollRewardResponse)(nil), "protocol.CMsgClientToGCCandyShopRerollRewardResponse")
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_candy_shop.proto", fileDescriptor_132364ac0874755d)
}

var fileDescriptor_132364ac0874755d = []byte{
	// 1109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xef, 0x3a, 0xfd, 0xb0, 0x9f, 0x71, 0x62, 0xa6, 0x5f, 0x26, 0x49, 0x49, 0xb3, 0x90, 0x50,
	0x8a, 0xea, 0x88, 0x1c, 0x10, 0x0d, 0x2d, 0xa8, 0xb1, 0xad, 0xd4, 0x07, 0x42, 0xd9, 0xb8, 0x95,
	0x8a, 0x90, 0x56, 0xe3, 0xdd, 0x17, 0x7b, 0x65, 0xef, 0xce, 0x32, 0x33, 0x9b, 0xd6, 0x3d, 0xe5,
	0xc0, 0x09, 0x71, 0x47, 0xe2, 0xc8, 0x8d, 0x3b, 0x47, 0xfe, 0x01, 0xee, 0xfc, 0x39, 0x1c, 0xd0,
	0xce, 0x7e, 0xd8, 0xce, 0xfa, 0x2b, 0x02, 0x41, 0x4e, 0xd9, 0x79, 0xf3, 0x7e, 0xef, 0xe3, 0xf7,
	0xde, 0xbc, 0x3c, 0xc3, 0x07, 0x36, 0x93, 0xd4, 0xec, 0x58, 0x2e, 0x0a, 0x41, 0x3b, 0x28, 0x4c,
	0xab, 0xef, 0xa0, 0x27, 0x4d, 0x8b, 0x7a, 0xf6, 0xc0, 0x14, 0x5d, 0xe6, 0x57, 0x7d, 0xce, 0x24,
	0x23, 0x79, 0xf5, 0xc7, 0x62, 0xfd, 0xd5, 0xeb, 0x42, 0x22, 0x75, 0x13, 0x40, 0x74, 0xbd, 0x7a,
	0x5b, 0xd9, 0x11, 0x5d, 0xca, 0xd1, 0x36, 0xd1, 0x0b, 0xdc, 0xe4, 0x62, 0x3d, 0xe3, 0x80, 0xb9,
	0x2e, 0xf3, 0xa6, 0xdd, 0xbe, 0xc2, 0x36, 0xf5, 0x9d, 0xf8, 0xf6, 0x56, 0xc7, 0x12, 0x76, 0x6f,
	0xe4, 0x3a, 0x96, 0xdf, 0x6c, 0x53, 0x81, 0x13, 0xc4, 0x68, 0x31, 0x2f, 0x2b, 0x5e, 0x9f, 0x9c,
	0x62, 0x02, 0x3a, 0xa1, 0xfd, 0x13, 0xc4, 0xd7, 0x12, 0x3d, 0xe1, 0x30, 0x2f, 0x06, 0xe9, 0x2f,
	0xe1, 0x76, 0xed, 0x4b, 0xd1, 0xa9, 0x85, 0x34, 0x1c, 0x75, 0x99, 0xaf, 0x3e, 0x6a, 0x2c, 0xf0,
	0x24, 0xb9, 0x03, 0x10, 0xb1, 0x23, 0x07, 0x3e, 0x56, 0xb4, 0xbb, 0xda, 0xbd, 0x92, 0x51, 0x50,
	0x92, 0xd6, 0xc0, 0x47, 0xb2, 0x01, 0xc5, 0xe8, 0xda, 0x0a, 0xb5, 0x2b, 0x39, 0x75, 0x1f, 0x21,
	0x14, 0x5e, 0x6f, 0xc3, 0x6a, 0xd6, 0xf4, 0xd7, 0x01, 0xf5, 0xa4, 0x23, 0x07, 0xa4, 0x0e, 0x6f,
	0x8d, 0xc0, 0x45, 0x45, 0xbb, 0xbb, 0x74, 0xaf, 0xb8, 0xbb, 0x59, 0x4d, 0xe8, 0xaf, 0x4e, 0x09,
	0xcb, 0x28, 0x0e, 0x5d, 0x08, 0xfd, 0x37, 0x0d, 0xd6, 0xc6, 0x14, 0x1b, 0xaf, 0xad, 0x2e, 0xf5,
	0x3a, 0x68, 0xa0, 0xe5, 0xf8, 0x48, 0xd6, 0xa0, 0xc0, 0xd5, 0x97, 0xe9, 0xd8, 0x2a, 0x85, 0xcb,
	0x46, 0x3e, 0x12, 0x34, 0x6d, 0xb2, 0x07, 0x57, 0x1c, 0xcf, 0x0f, 0xa2, 0xd8, 0x8b, 0xbb, 0xef,
	0xcf, 0xf2, 0x9d, 0xc4, 0x6d, 0x44, 0x10, 0xf2, 0x08, 0xae, 0xb2, 0x40, 0x86, 0xe0, 0xa5, 0x73,
	0x80, 0x63, 0x8c, 0xfe, 0x10, 0xd6, 0xc7, 0xb4, 0x0c, 0x7c, 0x45, 0xb9, 0x5d, 0xa7, 0x92, 0x9a,
	0x4d, 0x89, 0x2e, 0x79, 0x07, 0xf2, 0x8e, 0x44, 0xd7, 0xb4, 0xf1, 0x38, 0x26, 0xfe, 0x5a, 0x78,
	0xae, 0xe3, 0xb1, 0xfe, 0xb3, 0x06, 0xef, 0x4d, 0xc3, 0x36, 0x4e, 0xd0, 0x93, 0x4f, 0x2c, 0xe9,
	0x30, 0x8f, 0xec, 0x41, 0x1e, 0xc3, 0x63, 0x92, 0xf8, 0xf2, 0x6e, 0x79, 0x18, 0x62, 0x43, 0x69,
	0xee, 0x95, 0x1a, 0x2f, 0x1a, 0x87, 0x2d, 0xb3, 0x59, 0x37, 0x0f, 0xbf, 0x3a, 0x6c, 0x18, 0xd7,
	0x14, 0xa0, 0x69, 0x87, 0xac, 0x51, 0x65, 0x25, 0x04, 0x47, 0x85, 0xcd, 0x47, 0x82, 0xa6, 0x4d,
	0x56, 0x21, 0xff, 0x5d, 0x9c, 0x8f, 0xca, 0xbd, 0x64, 0xa4, 0x67, 0xfd, 0xa7, 0xdc, 0x99, 0x76,
	0x8a, 0x82, 0x53, 0x39, 0x7d, 0x0b, 0x45, 0xae, 0x4e, 0xc3, 0x7e, 0x5a, 0xde, 0x7d, 0x77, 0x24,
	0xa6, 0x33, 0xa0, 0xb0, 0xc9, 0xf6, 0xd6, 0x7a, 0x26, 0x4e, 0x90, 0x9b, 0x87, 0xcc, 0x43, 0x03,
	0x78, 0x2a, 0x20, 0x35, 0x28, 0x44, 0x8c, 0x51, 0x49, 0xe3, 0x7a, 0x6e, 0x4f, 0x29, 0xc9, 0x19,
	0xb2, 0x0d, 0x45, 0x75, 0x78, 0x24, 0x2f, 0xe1, 0xed, 0x88, 0xb3, 0x38, 0x7b, 0x65, 0x2c, 0xaa,
	0xef, 0x83, 0xf9, 0xc6, 0x46, 0xd8, 0x37, 0x56, 0x70, 0x78, 0x08, 0x2f, 0xf5, 0x5f, 0x35, 0xb8,
	0x3e, 0x01, 0x18, 0x35, 0xa8, 0x62, 0x65, 0xb4, 0x41, 0x15, 0x69, 0xaa, 0x41, 0x7d, 0xee, 0x58,
	0x78, 0xbe, 0x06, 0x55, 0x10, 0xf2, 0x10, 0xae, 0x46, 0x76, 0xe2, 0x04, 0x36, 0x67, 0x26, 0xa0,
	0x88, 0x88, 0x01, 0xfa, 0x9f, 0x39, 0xb8, 0x39, 0xa6, 0xf3, 0x5c, 0x20, 0x57, 0x04, 0x6d, 0xc1,
	0xb2, 0xe3, 0x85, 0x99, 0x31, 0x3e, 0x30, 0x85, 0xf3, 0x26, 0x19, 0x0b, 0xa5, 0x54, 0x7a, 0xe4,
	0xbc, 0x41, 0xb2, 0x0f, 0x85, 0x54, 0x70, 0xae, 0xd8, 0x87, 0x30, 0xf2, 0x29, 0x54, 0x30, 0x7e,
	0xcb, 0x26, 0x47, 0x81, 0xd2, 0x94, 0x8e, 0x8b, 0x42, 0x52, 0xd7, 0x57, 0x19, 0x5d, 0x33, 0x6e,
	0x61, 0xfa, 0xd6, 0x05, 0xca, 0x56, 0x72, 0x4b, 0x9e, 0x41, 0x79, 0x04, 0x19, 0xbe, 0x75, 0x51,
	0xb9, 0xac, 0xa6, 0xcb, 0xd6, 0x94, 0x20, 0xc6, 0x87, 0x86, 0xb1, 0x82, 0x63, 0x67, 0x41, 0xea,
	0xb0, 0x1c, 0x76, 0xc4, 0x49, 0x68, 0x2f, 0x64, 0x48, 0x54, 0xae, 0x28, 0x7b, 0x77, 0x66, 0x72,
	0x6a, 0x94, 0x22, 0x50, 0x74, 0x12, 0xfa, 0x53, 0xd0, 0x95, 0x96, 0x9a, 0xca, 0x2d, 0x76, 0x50,
	0x4b, 0xf5, 0x0f, 0x50, 0xa6, 0x14, 0xeb, 0x50, 0x1a, 0xfe, 0x4f, 0x4a, 0x9a, 0xa2, 0x14, 0x4f,
	0xbd, 0x50, 0xb9, 0x69, 0xeb, 0xbf, 0xe7, 0xe0, 0xfe, 0x7c, 0x53, 0x06, 0x0a, 0x9f, 0x79, 0x02,
	0x49, 0x1f, 0xf2, 0x3c, 0xfe, 0x8e, 0x9f, 0xdd, 0xe7, 0x67, 0x02, 0x5f, 0xc8, 0x4e, 0xb5, 0x91,
	0x7c, 0xed, 0x95, 0x7b, 0x26, 0x36, 0x3d, 0x89, 0xdc, 0xa3, 0xfd, 0x06, 0xe7, 0x8c, 0x1b, 0xa9,
	0x07, 0xf2, 0x08, 0x0a, 0x81, 0x40, 0x3e, 0xfa, 0x12, 0x37, 0xa6, 0xf0, 0x94, 0x7a, 0xc8, 0x07,
	0xf1, 0x97, 0xde, 0x86, 0x42, 0xea, 0x86, 0xdc, 0x80, 0x8c, 0xa3, 0xf2, 0x25, 0xb2, 0x0c, 0xd0,
	0x33, 0xf1, 0x28, 0xb0, 0x2c, 0x14, 0xa2, 0xac, 0xc5, 0xe7, 0x16, 0x63, 0xfb, 0x81, 0x18, 0x94,
	0x73, 0x64, 0x05, 0x8a, 0x3d, 0x13, 0xeb, 0x8e, 0xa0, 0xed, 0x3e, 0xda, 0xe5, 0xa5, 0x44, 0xc1,
	0x71, 0x91, 0x05, 0xb2, 0x7c, 0x59, 0xff, 0x41, 0x83, 0xed, 0x30, 0x8e, 0x83, 0x5a, 0x8b, 0x45,
	0xa9, 0x67, 0x22, 0x7a, 0xee, 0xdb, 0x54, 0xa2, 0xbd, 0x48, 0x35, 0xfe, 0x61, 0xc2, 0x5d, 0xd8,
	0x9a, 0x52, 0x82, 0x67, 0x01, 0xb7, 0xba, 0x54, 0xc4, 0xfd, 0xb3, 0x50, 0x28, 0x63, 0xd3, 0x24,
	0x37, 0x3e, 0x4d, 0xf4, 0xef, 0x73, 0xf0, 0x60, 0x21, 0x57, 0x29, 0xff, 0x2c, 0xd3, 0x38, 0x4f,
	0xe6, 0x36, 0xce, 0x64, 0x53, 0x8b, 0xf5, 0xce, 0x7f, 0x52, 0x7d, 0x1b, 0x36, 0xa7, 0x84, 0x5e,
	0x67, 0xc9, 0x20, 0x58, 0x9c, 0xec, 0x64, 0xb7, 0xc8, 0x8d, 0xef, 0x16, 0xfa, 0x5f, 0x1a, 0x7c,
	0x38, 0xd7, 0x4d, 0x9a, 0x6a, 0x2f, 0x43, 0xf4, 0xe3, 0xb9, 0x44, 0x67, 0xcd, 0x5c, 0x20, 0x92,
	0xff, 0x98, 0x95, 0xfe, 0x0b, 0xca, 0x9d, 0x10, 0x78, 0x2e, 0xb6, 0xff, 0xbf, 0x65, 0xed, 0xc7,
	0x1c, 0x7c, 0xbc, 0x70, 0x2e, 0x29, 0xb1, 0x22, 0x53, 0xd2, 0xc6, 0x02, 0x25, 0x9d, 0x66, 0xee,
	0x02, 0x95, 0xf6, 0x97, 0x64, 0x01, 0xcd, 0xc6, 0x6f, 0x20, 0x67, 0xfd, 0xfe, 0xbf, 0x34, 0xaf,
	0x86, 0xdb, 0xcf, 0xd2, 0xb9, 0xb7, 0x1f, 0xfd, 0x34, 0x07, 0x1f, 0x2d, 0x10, 0x64, 0xca, 0x95,
	0x9b, 0xa9, 0xd6, 0x17, 0x73, 0xab, 0x35, 0xc9, 0xd0, 0xc5, 0xa9, 0xd3, 0xfd, 0x53, 0x0d, 0x6e,
	0x4c, 0xda, 0xa9, 0xc9, 0x06, 0xcc, 0xda, 0xaa, 0xcb, 0x97, 0x66, 0x28, 0x84, 0x6b, 0x62, 0x59,
	0x23, 0xdb, 0xa0, 0x4f, 0x51, 0x18, 0xd9, 0x81, 0xcb, 0xb9, 0xfd, 0xc7, 0x4f, 0xb5, 0x6f, 0x3e,
	0xe9, 0x30, 0xd6, 0xe9, 0x63, 0xb5, 0xc3, 0xfa, 0xd4, 0xeb, 0x54, 0x19, 0xef, 0xec, 0x28, 0x62,
	0xdb, 0xc1, 0xf1, 0x4e, 0xf8, 0x43, 0x40, 0xec, 0xd8, 0x28, 0x2c, 0xee, 0xf8, 0x92, 0x71, 0xbf,
	0xfd, 0x59, 0x42, 0xfa, 0xa9, 0x76, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xda, 0x6e,
	0xe7, 0xb4, 0x0f, 0x00, 0x00,
}
